modLoader = "javafml"
loaderVersion = "[48,)"
license = "LGPL-3.0-only"

[[mods]]
    modId = "sequoia"
    version = "${version}" #Version is added in build.gradle
    displayName = "Sequoia"
    authors = "Lotnest"
    description = "Guild mod for Sequoia [SEQ]."
    logoFile = "assets/sequoia/logo.png"

[[dependencies.sequoia]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.2]"

[[dependencies.sequoia]]
    modId = "forge"
    mandatory = true
    versionRange = "[48.0.0,)"

