modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0-only"

[[mods]]
modId = "sequoia"
version = "${version}"
displayName = "Sequoia"
authors = "Lotnest (Owner & Lead Developer), Iriya_ (Mod Developer), dotJJ (Server Developer) and OwORawr (Sequoia OST composer)"
description = "Guild mod for Sequoia [SEQ]."
logoFile = "assets/sequoia/sequoia-icon.png"

[[dependencies.sequoia]]
modId = "minecraft"
mandatory = true
versionRange = "1.21.4"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sequoia]]
modId = "forge"
mandatory = true
versionRange = "1.21.4"

[[mixins]]
config = "sequoia.mixins.json"
