modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "LGPL-3.0-only"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "Sequoia"
    authors = "Lotnest (Mod Developer), OwORawr (Sequoia OST composer)"
    description = "Guild mod for Sequoia [SEQ]."
    logoFile = "assets/sequoia/logo.png"

[[dependencies.sequoia]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_version}]"

[[dependencies.sequoia]]
    modId = "forge"
    mandatory = true
    versionRange = "${neoforge_version_range}"

[[mixins]]
config = "sequoia.mixins.json"

[[mixins]]
config = "sequoia.mixins.neoforge.json"
